# -*- coding: utf-8 -*-
"""DS-GEN AI internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tb7rUkaSa4xqThakckgSfo_PCbQWqVL4

#Task-1
"""

def mimic_upper(str):
    if len(str) == 0:
        return str
    else:
        result = ""
        for i in str:
            if "a"<=i<="z":
                result += chr(ord(i)-32)
            else:
                result += i
    return result











#using str upper
def my_startswith(text, prefix):
    if len(text) < len(prefix):
        return False

    for i in range(len(prefix)):
        if text[i] != prefix[i]:
            return False
    return True
my_startswith('hello','bro')

#using str lower
def my_upper(text):
    result = ""
    for ch in text:
        if 'a' <= ch <= 'z':
            result += chr(ord(ch) - 32)
        else:
            result += ch
    return result
print(my_upper('hello'))

#capitalize code
def word_capitalize(text):
    if text == "":
        return ""
    result = ""
    first = text[0]
    if 'a' <= first <= 'z':
        result += chr(ord(first)-32)
    else:
        result += first
    for ch in text[1:]:
        if 'A' <= ch <= 'Z':
            result += chr(ord(ch)+32)
        else:
            result += ch
    return result


word_capitalize("heLLo")

#string swapcase
def my_swapcase(text):
    result = ""
    for ch in text:
        if 'a' <= ch <= 'z':
            result += chr(ord(ch) - 32)
        elif 'A' <= ch <= 'Z':
            result += chr(ord(ch) + 32)
        else:
            result += ch
    return result
print(my_swapcase('HeLlo'))

#Title
def my_title(text):
    result = ""
    nw = True
    for ch in text:
        if ch == " ":
            nw = True
            result += ch
        else:
            if nw and 'a' <= ch <= 'z':
                result += chr(ord(ch)-32)
            elif not nw and 'A' <= ch <= 'Z':
                result += chr(ord(ch)+32)
            else:
                result += ch
            nw = False
    return result
my_title("hello world program")

#my_reverse
def my_reverse(text):
    r=""
    for i in range(len(text)-1,-1,-1):
        r+=text[i]
    return r
my_reverse("Python")

#my_isalpha
def my_isalpha(text):
    for ch in text:
        if not(('a'<=ch<='z') or ('A'<=ch<='Z')):
            return False
    return True
my_isalpha("Hello")

#count
def my_count(text, sub):
    c=0
    for i in range(len(text)-len(sub)+1):
        ok=True
        for j in range(len(sub)):
            if text[i+j]!=sub[j]:
                ok=False
                break
        if ok: c+=1
    return c
my_count("banana","ana")

#my_split(text, delimiter)
def my_split(text, d):
    arr=[]
    cur=""
    for ch in text:
        if ch==d:
            arr.append(cur)
            cur=""
        else:
            cur+=ch
    arr.append(cur)
    return arr
my_split("a,b,c",",")

#Join
def my_join(lst, sep):
    r=""
    for i in range(len(lst)):
        r+=lst[i]
        if i<len(lst)-1:
            r+=sep
    return r
my_join(["a","b","c"],"-")

#Compress
def my_compress(text):
    if text=="": return ""
    r=""
    c=1
    for i in range(1,len(text)):
        if text[i]==text[i-1]:
            c+=1
        else:
            r+=text[i-1]+str(c)
            c=1
    r+=text[-1]+str(c)
    return r
my_compress("aaabbc")

"""#Task -2"""

#1. Running Sum of 1d Array
def runningSum(nums):
    run = 0
    result = []
    for n in nums:
        run += n
        result.append(run)
    return result

runningSum([1,2,3,4])

#2. Shuffle the Array
def shuffle(nums, n):
    result = []
    for i in range(n):
        result.append(nums[i])
        result.append(nums[i + n])
    return result

shuffle([2,5,1,3,4,7], 3)

#3. Kids With the Greatest Number of Candies
def kidsWithCandies(candies, extraCandies):
    max_candy = max(candies)
    return [(c + extraCandies) >= max_candy for c in candies]

kidsWithCandies([2,3,5,1,3], 3)